import {create} from 'zustand'; import {workflows as seed} from '../../mock-data/workflows'; import {instances} from '../../mock-data/instances'; import type {FlowEdge,FlowNode,ValidationIssue,Workflow} from '../types'; import {checkUpgrade,getRef} from '../lib/subflow';
const clone=<T,>(x:T):T=>JSON.parse(JSON.stringify(x));
const validate=(w:Workflow):ValidationIssue[]=>{const issues:ValidationIssue[]=[]; if(!w.nodes.some(n=>n.type==='end')) issues.push({nodeId:w.nodes[0]?.id||'flow',level:'error',message:'流程缺少结束节点'}); const linked=new Set(w.edges.flatMap(e=>[e.source,e.target])); w.nodes.filter(n=>n.type!=='start'&&n.type!=='end'&&!linked.has(n.id)).forEach(n=>issues.push({nodeId:n.id,level:'error',message:'必经节点不能孤立'})); w.nodes.forEach(n=>{if(n.type==='condition'&&!n.data.config.ruleType)issues.push({nodeId:n.id,level:'error',message:'条件分支规则未配置'}); if(n.type==='approval'&&!n.data.config.approverSource)issues.push({nodeId:n.id,level:'error',message:'审批人不能为空'});}); return issues};
const patchNode=(w:Workflow,nodeId:string,patch:Partial<FlowNode>)=>w.nodes.map(n=>n.id===nodeId?{...n,...patch}:n);
const setRefCheck=(w:Workflow,nodeId:string,check:NonNullable<ReturnType<typeof getRef>>['check'])=>patchNode(w,nodeId,{data:{...w.nodes.find(n=>n.id===nodeId)!.data,config:{...w.nodes.find(n=>n.id===nodeId)!.data.config,check}}});
interface State{workflows:Workflow[];instances:typeof instances;currentId:string;selectedNodeId:string|null;issues:ValidationIssue[];toast:string;setCurrent:(id:string)=>void;selectNode:(id:string|null)=>void;updateNodes:(nodes:FlowNode[])=>void;updateEdges:(edges:FlowEdge[])=>void;updateConfig:(id:string,config:Record<string,any>)=>void;runValidation:()=>ValidationIssue[];save:()=>void;publish:()=>void;create:()=>string;copy:(id:string)=>void;archive:(id:string)=>void;restore:(v:number)=>void;insertSubflow:(sourceId:string)=>void;checkSubflowUpgrade:(nodeId:string)=>void;confirmSubflowUpgrade:(nodeId:string)=>void;clearToast:()=>void}
export const useAppStore=create<State>((set,get)=>({workflows:clone(seed),instances,currentId:'wf-1',selectedNodeId:null,issues:[],toast:'',setCurrent:id=>set({currentId:id,selectedNodeId:null,issues:[]}),selectNode:id=>set({selectedNodeId:id}),updateNodes:nodes=>set(s=>({workflows:s.workflows.map(w=>w.id===s.currentId?{...w,nodes}:w)})),updateEdges:edges=>set(s=>({workflows:s.workflows.map(w=>w.id===s.currentId?{...w,edges}:w)})),updateConfig:(id,config)=>set(s=>({workflows:s.workflows.map(w=>w.id===s.currentId?{...w,nodes:w.nodes.map(n=>n.id===id?{...n,data:{...n.data,config:{...n.data.config,...config},state:'configuring'}}:n)}:w)})),runValidation:()=>{const w=get().workflows.find(x=>x.id===get().currentId)!; const issues=validate(w); set(s=>({issues,workflows:s.workflows.map(x=>x.id===w.id?{...x,nodes:x.nodes.map(n=>({...n,data:{...n.data,state:issues.some(i=>i.nodeId===n.id)?'invalid':'valid'}}))}:x),toast:issues.length?`发现 ${issues.length} 个问题`:'校验通过'}));return issues},save:()=>set(s=>({workflows:s.workflows.map(w=>w.id===s.currentId?{...w,status:'draft',updatedAt:'2026-07-11 16:30'}:w),toast:'草稿已保存'})),publish:()=>set(s=>({workflows:s.workflows.map(w=>w.id===s.currentId?{...w,status:'published',version:w.version+1,publishedAt:'2026-07-11 16:35',updatedAt:'2026-07-11 16:35',versions:[...w.versions,{version:w.version+1,createdAt:'2026-07-11 16:35',note:'发布最新审批配置',nodes:clone(w.nodes),edges:clone(w.edges)}]}:w),toast:'流程发布成功'})),create:()=>{const id='wf-'+Date.now();set(s=>({workflows:[{id,name:'未命名流程',domain:'财务',status:'draft',version:0,editor:'林秋',updatedAt:'2026-07-11 16:40',abnormalCount:0,nodes:[],edges:[],versions:[]},...s.workflows],currentId:id}));return id},copy:id=>set(s=>{const w=s.workflows.find(x=>x.id===id)!;return{workflows:[{...clone(w),id:'wf-'+Date.now(),name:w.name+'（副本）',status:'draft'},...s.workflows]}}),archive:id=>set(s=>({workflows:s.workflows.map(w=>w.id===id?{...w,status:'archived'}:w)})),restore:v=>set(s=>({workflows:s.workflows.map(w=>{if(w.id!==s.currentId)return w;const old=w.versions.find(x=>x.version===v)!;return{...w,status:'draft',nodes:clone(old.nodes),edges:clone(old.edges)}}),toast:`已恢复 v${v} 为草稿`})),
 insertSubflow:sourceId=>set(s=>{
  const source=s.workflows.find(w=>w.id===sourceId);const parent=s.workflows.find(w=>w.id===s.currentId);
  if(!source||!parent)return {};
  if(source.status!=='published')return {toast:'已归档或草稿流程不能作为受控子流程插入'};
  const latest=[...source.versions].sort((a,b)=>b.version-a.version)[0];
  if(!latest.nodes.some(x=>x.type==='end'))return {toast:`${source.name} 最新发布版本缺少结束节点，不能插入`};
  const node:FlowNode={id:'subflow-'+Date.now(),type:'subflow',position:{x:300+Math.random()*160,y:160+Math.random()*120},data:{label:source.name+'（受控）',state:'valid',config:{sourceId:source.id,sourceName:source.name,pinnedVersion:latest.version,insertedVersion:latest.version,runningInstances:0}}};
  const anchor=parent.nodes.find(n=>n.id===s.selectedNodeId&&n.type!=='end'&&n.type!=='condition'&&!parent.edges.some(e=>e.source===n.id));
  const edges=anchor?[...parent.edges,{id:'e-'+Date.now(),source:anchor.id,target:node.id,label:`${source.name} v${latest.version}`}]:parent.edges;
  return {workflows:s.workflows.map(w=>w.id===parent.id?{...w,nodes:[...w.nodes,node],edges}:w),selectedNodeId:node.id,toast:`已插入 ${source.name}，锁定已发布版本 v${latest.version}`};
 }),
 checkSubflowUpgrade:nodeId=>set(s=>{
  const parent=s.workflows.find(w=>w.id===s.currentId)!;const node=parent.nodes.find(n=>n.id===nodeId)!;
  const r=checkUpgrade(parent,node,s.workflows);
  if(r.status==='up-to-date')return {toast:'当前锁定版本已是最新发布版本'};
  const check={targetVersion:r.targetVersion,status:r.status,gaps:r.gaps,checkedAt:'2026-07-11 16:40'} as const;
  return {workflows:s.workflows.map(w=>w.id===parent.id?{...w,nodes:setRefCheck(w,nodeId,check)}:w),toast:r.status==='ready'?`已确认可升级到 v${r.targetVersion}，等待执行升级`:`升级检查未通过：${r.gaps.length} 项缺口，已留在待处理`};
 }),
 confirmSubflowUpgrade:nodeId=>set(s=>{
  const parent=s.workflows.find(w=>w.id===s.currentId)!;const node=parent.nodes.find(n=>n.id===nodeId)!;const ref=getRef(node);
  if(!ref)return {};
  const r=checkUpgrade(parent,node,s.workflows);
  if(r.status==='blocked'||r.status==='up-to-date')return {toast:r.status==='up-to-date'?'当前已是最新版本':'仍有接入点缺口未修复，不能升级'};
  return {workflows:s.workflows.map(w=>w.id===parent.id?{...w,nodes:w.nodes.map(n=>n.id===nodeId?{...n,data:{...n.data,config:{...n.data.config,pinnedVersion:r.targetVersion,check:undefined}}} :n)}:w),toast:`已升级到 ${ref.sourceName} v${r.targetVersion}；${ref.runningInstances} 个存量实例仍按 v${ref.insertedVersion} 运行`};
 }),
 clearToast:()=>set({toast:''})}));
